name: test Login Serv00 Command

on:
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai
jobs:
  run-ssh-command:
    runs-on: ubuntu-latest
   
    steps:
      - name: 检查仓库
        uses: actions/checkout@v2
      - name: 登录面板
        run: |  
          login_and_check() {
          local username=$1
          local panel_url=$2
          # 获取 CSRF 认证值和 CSRF token 值
          response=$(curl -Lksi "$panel_url/login")
          csrftoken=$(echo "$response" | sed -n 's/.*csrftoken=\([^;]*\);.*/\1/p')
          csrfmiddlewaretoken=$(echo "$response" | sed -n 's/.*<input type="hidden" name="csrfmiddlewaretoken" value="\([^"]*\)".*/\1/p' | head -n 1)
          echo -e "\033[36;1mcsrfmiddlewaretoken=\033[0m\033[35;1m$csrfmiddlewaretoken \033[0m"
          echo -e "\033[36;1mcsrftoken=\033[0m\033[35;1m$csrftoken \033[0m"

          # 获取 sessionid 值
          curl -ki "$panel_url/login/?next=/" \
          -H "Referer: $panel_url/login/" \
          -H "Cookie: csrftoken=$csrftoken" \
          -d "csrfmiddlewaretoken=$csrfmiddlewaretoken&username=$username&password=${{ secrets.SSH_PRIVATE_KEY }}"
          
             
         
          }

          # 依次执行登录
                                                                                                               
          login_and_check "${{ secrets.USER1 }}" "https://panel4.serv00.com"                                                                                                              
                                                                                                                   
