name: test Login Serv00 Command

on:
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H s4.serv00.com >> ~/.ssh/known_hosts

      - name: Run remote script
        run: |
          ssh ${{ secrets.USER1 }}@s4.serv00.com 'bash ./tool/vnts.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                           
